extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport/TestAutomationReport.html
extent.reporter.spark.config=src/test/resources/extent-config.xml
extent.reporter.spark.enable.author=true
extent.reporter.spark.prefix.author=@aut_
extent.reporter.spark.vieworder=dashboard,test,category,exception,author
systeminfo.OS=Windows
systeminfo.Version=10
systeminfo.Programming_Language=Java
extent.reporter.spark.base64imagesrc=true